-- 魂募集サイトテンプレート 初期設定SQL
-- 実行前に、このファイル内の YOUR_EMAIL@example.com を管理者メールに全置換してください。

create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.characters (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  display_order integer not null default 1 check (display_order > 0),
  description text not null default '',
  illustration_price integer check (illustration_price is null or illustration_price >= 0),
  live2d_price integer check (live2d_price is null or live2d_price >= 0),
  full_price integer check (full_price is null or full_price >= 0),
  price_note text not null default '',
  status text not null default 'preparing' check (status in ('preparing','available','sold')),
  is_published boolean not null default false,
  face_image_url text not null,
  full_image_url text not null,
  video_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.characters add column if not exists video_url text;
create index if not exists characters_display_idx on public.characters(is_published,display_order);

create table if not exists public.character_interests (
  character_id uuid not null references public.characters(id) on delete cascade,
  visitor_id uuid not null,
  created_at timestamptz not null default now(),
  primary key(character_id,visitor_id)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  event_name text not null check(event_name in ('page_view','character_view','interest_click','inquiry_click')),
  session_id uuid not null,
  character_id uuid references public.characters(id) on delete set null,
  page text not null default '/',
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  occurred_at timestamptz not null default now()
);
create index if not exists analytics_events_time_idx on public.analytics_events(occurred_at desc);
create index if not exists analytics_events_character_idx on public.analytics_events(character_id,occurred_at desc) where character_id is not null;

alter table public.site_settings enable row level security;
alter table public.characters enable row level security;
alter table public.character_interests enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "settings public read" on public.site_settings;
create policy "settings public read" on public.site_settings for select to anon,authenticated using(true);
drop policy if exists "admin inserts settings" on public.site_settings;
create policy "admin inserts settings" on public.site_settings for insert to authenticated
with check(lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));
drop policy if exists "admin updates settings" on public.site_settings;
create policy "admin updates settings" on public.site_settings for update to authenticated
using(lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'))
with check(lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));

drop policy if exists "published characters public read" on public.characters;
create policy "published characters public read" on public.characters for select to anon,authenticated
using(is_published or lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));
drop policy if exists "admin inserts characters" on public.characters;
create policy "admin inserts characters" on public.characters for insert to authenticated
with check(lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));
drop policy if exists "admin updates characters" on public.characters;
create policy "admin updates characters" on public.characters for update to authenticated
using(lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'))
with check(lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));
drop policy if exists "admin deletes characters" on public.characters;
create policy "admin deletes characters" on public.characters for delete to authenticated
using(lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));

drop policy if exists "admin reads analytics" on public.analytics_events;
create policy "admin reads analytics" on public.analytics_events for select to authenticated
using(lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));

grant select,insert,update on public.site_settings to authenticated;
grant select on public.site_settings to anon;
grant select on public.characters to anon;
grant select,insert,update,delete on public.characters to authenticated;
grant select on public.analytics_events to authenticated;
grant usage,select on all sequences in schema public to anon,authenticated;

insert into public.site_settings(key,value) values
('site_name','あなたのブランド名'),('site_title','魂募集'),
('site_description','気になるキャラクターを見つけてください。'),
('form_url',''),('accent_color','#6c5cff'),('frame_style','soft'),
('icon_url',''),('background_url','') on conflict(key) do nothing;

create or replace function public.get_public_characters()
returns jsonb language sql stable security definer set search_path=pg_catalog as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',c.id,'name',c.name,'display_order',c.display_order,'description',c.description,
    'illustration_price',c.illustration_price,'live2d_price',c.live2d_price,
    'full_price',c.full_price,'price_note',c.price_note,'status',c.status,
    'is_published',c.is_published,'face_image_url',c.face_image_url,'full_image_url',c.full_image_url,
    'video_url',c.video_url,
    'interest_count',(select count(*) from public.character_interests i where i.character_id=c.id)
  ) order by c.display_order,c.created_at),'[]'::jsonb)
  from public.characters c where c.is_published
$$;
revoke all on function public.get_public_characters() from public;
grant execute on function public.get_public_characters() to anon,authenticated;

create or replace function public.toggle_site_interest(p_character_id uuid,p_visitor_id uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog as $$
declare active boolean; total bigint;
begin
  if not exists(select 1 from public.characters c where c.id=p_character_id and c.is_published and c.status='available') then raise exception '受付中ではありません'; end if;
  delete from public.character_interests where character_id=p_character_id and visitor_id=p_visitor_id;
  if found then active:=false; else insert into public.character_interests(character_id,visitor_id) values(p_character_id,p_visitor_id) on conflict do nothing; active:=true; end if;
  select count(*) into total from public.character_interests where character_id=p_character_id;
  return jsonb_build_object('active',active,'count',total);
end $$;
revoke all on function public.toggle_site_interest(uuid,uuid) from public;
grant execute on function public.toggle_site_interest(uuid,uuid) to anon,authenticated;

create or replace function public.track_site_event(p_event_id uuid,p_event_name text,p_session_id uuid,p_character_id uuid default null,p_page text default '/',p_referrer text default null,p_utm_source text default null,p_utm_medium text default null,p_utm_campaign text default null)
returns void language plpgsql security definer set search_path=pg_catalog as $$
begin
  if p_event_name not in ('page_view','character_view','interest_click','inquiry_click') then raise exception 'invalid event'; end if;
  if p_character_id is not null and not exists(select 1 from public.characters c where c.id=p_character_id and c.is_published) then raise exception 'invalid character'; end if;
  insert into public.analytics_events(event_id,event_name,session_id,character_id,page,referrer,utm_source,utm_medium,utm_campaign)
  values(p_event_id,p_event_name,p_session_id,p_character_id,left(coalesce(p_page,'/'),500),left(p_referrer,1000),left(p_utm_source,200),left(p_utm_medium,200),left(p_utm_campaign,200))
  on conflict(event_id) do nothing;
end $$;
revoke all on function public.track_site_event(uuid,text,uuid,uuid,text,text,text,text,text) from public;
grant execute on function public.track_site_event(uuid,text,uuid,uuid,text,text,text,text,text) to anon,authenticated;

create or replace function public.get_admin_analytics(p_period text default '30d')
returns jsonb language plpgsql stable security definer set search_path=pg_catalog as $$
declare start_at timestamptz; result jsonb;
begin
 if lower(coalesce(auth.jwt()->>'email',''))<>lower('YOUR_EMAIL@example.com') then raise exception '管理者のみ利用できます'; end if;
 start_at:=case p_period when '7d' then now()-interval '7 days' when '30d' then now()-interval '30 days' else '1970-01-01'::timestamptz end;
 select jsonb_build_object('totals',jsonb_build_object(
   'page_views',count(*) filter(where e.event_name='page_view'),
   'unique_visitors',count(distinct e.session_id) filter(where e.event_name='page_view'),
   'character_views',count(*) filter(where e.event_name='character_view'),
   'inquiries',count(*) filter(where e.event_name='inquiry_click')),
   'characters',coalesce((select jsonb_agg(jsonb_build_object('name',c.name,
     'views',(select count(*) from public.analytics_events x where x.character_id=c.id and x.event_name='character_view' and x.occurred_at>=start_at),
     'interests',(select count(*) from public.character_interests i where i.character_id=c.id),
     'inquiries',(select count(*) from public.analytics_events x where x.character_id=c.id and x.event_name='inquiry_click' and x.occurred_at>=start_at)) order by c.display_order) from public.characters c),'[]'::jsonb)
 ) into result from public.analytics_events e where e.occurred_at>=start_at;
 return result;
end $$;
revoke all on function public.get_admin_analytics(text) from public;
grant execute on function public.get_admin_analytics(text) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('site-assets','site-assets',true,52428800,array['image/jpeg','image/png','image/webp','video/mp4','video/webm'])
on conflict(id) do update set public=excluded.public,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "site assets public read" on storage.objects;
create policy "site assets public read" on storage.objects for select to public using(bucket_id='site-assets');
drop policy if exists "admin uploads site assets" on storage.objects;
create policy "admin uploads site assets" on storage.objects for insert to authenticated
with check(bucket_id='site-assets' and lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));
drop policy if exists "admin updates site assets" on storage.objects;
create policy "admin updates site assets" on storage.objects for update to authenticated
using(bucket_id='site-assets' and lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'))
with check(bucket_id='site-assets' and lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));
drop policy if exists "admin deletes site assets" on storage.objects;
create policy "admin deletes site assets" on storage.objects for delete to authenticated
using(bucket_id='site-assets' and lower(coalesce((select auth.jwt())->>'email',''))=lower('YOUR_EMAIL@example.com'));

-- 完了後、SupabaseのAuthentication設定で公開URLをSite URLとRedirect URLに登録してください。
